IKE/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('IKEdata.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

IKEdata/urls.py
from django.urls import path

from IKEdata import views

app_name = 'IKEdata'

urlpatterns = [
    path('loginto/', views.loginto, name='login'),
    path('sign_out/', views.sign_out, name='sign_out'),
    path('collect/', views.collect, name='collect'),
    path('clean/', views.clean, name='clean'),
    path('analysis/', views.analysis, name='analysis'),
    path('analysis_test/', views.analysis_test, name='analysis_test'),
    path('mining/', views.mining, name='mining'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('wordnet/', views.wordnet, name='wordnet'),
    path('', views.dashboard, name='home'),
]

IKEdata/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.

class collect(models.Model):
    source_choice = (
        ('JD', '京东'),
        ('TEST', '测试数据'),
        ('OTHER', '其他'),
    )
    source = models.CharField(choices=source_choice, max_length=5, default='JD', verbose_name="数据来源")
    content = models.CharField(max_length=1000, verbose_name='内容')
    arthur = models.CharField(max_length=64,  verbose_name='作者')
    time = models.DateTimeField(auto_now_add=True, verbose_name='时间')
    link = models.CharField(max_length=64, verbose_name="链接")

# class autoabstract(models.Model):
#     source = (
#         ('JD', '京东'),
#         ('DCD', '懂车帝'),
#         ('Auto', '汽车之家'),
#     )
#     content = models.CharField(unique=True, verbose_name='内容')
#     arthur = models.CharField(max_length=64, unique=True, verbose_name='作者')
#     time = models.DateTimeField(auto_now_add=True, verbose_name='时间')
#     link = models.DateField(null=True, blank=True, verbose_name="链接")

IKEdata/views.py
import datetime
import json
import os

import pandas as pd
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.shortcuts import HttpResponse, redirect
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt

from IKE.settings import BASE_DIR
from IKEdata import asset_handler
from IKEdata import models
from . import extract2


def loginto(request):
    """
    登录
    :param request: username(str), password(str)
    :return: tips
    """
    una = request.POST.get('username', None)
    pwd = request.POST.get('password', None)
    if una and pwd:
        if User.objects.filter(username=una):
            user = authenticate(username=una, password=pwd)
            if user:
                if user.is_active:
                    login(request, user)
                    return redirect('IKEdata:dashboard')
                else:
                    tips = '账号未激活,请联系管理员'
            else:
                tips = '用户名或密码错误'
        else:
            tips = '用户不存在'
    else:
        tips = '请输入正确的账号和密码'
    return render(request, 'base.html', {'tips': tips, 'una': una})


def sign_out(request):
    if request.user.is_authenticated:
        logout(request)
        tips = '您已退出登录'
    else:
        return redirect('IKEdata:home')
    return render(request, 'base.html', {'tips': tips})


def dashboard(request):
    total_no = models.collect.objects.count()
    if total_no == 0:
        df = pd.read_excel(os.path.join(BASE_DIR, 'IKEdata/京东商品评论.xlsx'), sheet_name='Sheet1')
        for j in range(len(df.index.values)):
            i = j + 1
            content = df.iloc[i, 3]
            arthur = df.iloc[i, 0]
            time_string = df.iloc[i, 4]
            time = pd.to_datetime(time_string)
            link = df.iloc[i, 10]

            models.collect.objects.create(
                source='JD',
                content=content,
                arthur=arthur,
                time=time,
                link=link,
            )
    jd_no = models.collect.objects.filter(source='JD').count()
    test_no = models.collect.objects.filter(source='TEST').count()
    other_no = models.collect.objects.filter(source='OTHER').count()
    total_no = models.collect.objects.count()
    jd_data = round(jd_no / total_no * 100)
    test_data = round(test_no / total_no * 100)
    other_data = round(other_no / total_no * 100)
    positive_no = jd_no * 0.99
    negative_no = jd_no * 0.01
    current = 'dashboard'
    #     Input one page for text analysis
    return render(request, 'Container/Dashboard/index.html', locals())


def analysis_test(request):
    context = request.POST.get('context', None)
    extract_text = ''
    analysis_result = False
    current = 'analysis_test'
    if context:
        extract_text, keywords = extract2.extract(context)
        models.collect.objects.create(
            source='TEST',
            content=context.replace('\r', '').replace('\n', ''),
            arthur='',
            time=datetime.datetime.now(),
            link='',
        )
        analysis_result = True
        current = 'analysis_result'
    return render(
        request, 'Container/Analysis/analysisTest.html',
        {
            "context": context,
            "extract_text": extract_text,
            'analysis_result': analysis_result,
            'current': current,
        }
    )


def collect(request):
    """
    数据分析测试
    :param request:
    :return:
    """
    #   Display all comments: Source, Content, Time, link
    all_data = models.collect.objects.all()
    # current_page = request.GET.get('p', 1)
    # paginator = Paginator(all_data, 100)
    # try:
    #     page_obj = paginator.page(current_page)
    # except EmptyPage as e:
    #     page_obj = paginator.page(1)
    # except PageNotAnInteger as not_int_err:
    #     page_obj = paginator.page(1)
    return render(request, 'Container/Collect/index.html', {"all_data": all_data, "current": "collect"})


def clean(request):
    #   DataClean data
    return render(request, 'Container/Clean/index.html', {"current": "clean"})


def analysis(request):
    # df = pd.read_excel('D:\Python\Project\IKE\IKEdata\京东商品评论.xlsx', sheet_name='Sheet1')
    # comments = ''
    # for j in range(len(df.index.values)):
    #     i = j + 1
    #     content = df.iloc[i, 3]
    #     comments = comments + content
    #     if i == 999:
    #         exit()
    # extract_text = analyse_text.extract(comments)
    #   Display key words, word cloud, word net, text abstract
    
    context = "用了以后再追评一直用这个机油给车子保养，非常不错，相信京东自营。不错，美孚一号大牌子，京东自营值得信赖，爱车非常适用，已经用好多次京东买了，顺便购买了更换机油服务，一步到位，发动机很安静，油耗也降低了一点点，谁用谁知道，希望多搞点活动。一直用的银美孚一号 价格合适 自己保养车更放心 物流很快 一直信赖京东自营的东西选机油，先选SN级的，这是最高级，SL级是低配款，0W-30的意思是机油适用零度，流动性30的。家中常备机油，便宜就先囤一个，一直用这个牌子推荐这家店铺非常不错哦第一次在京东平台上购买美孚一号，之前一直在市场上买，效果特别好，希望京东平台上的美孚保真保质，如果用的好，以后还会接着在京东上购买京东平台优惠力度大，值得推荐，大家快来抢购，以后还会在京东上购买，希望以后赠送礼品多点首先，金美孚一号这款油，一直用这个牌子，质量非常好，其次，京东自营下单，配送时效特别快，晚上下单第二天早上9点就收到了，省去了去实体店的苦恼，而且价格也非常优惠，有优惠券可以领，这款油保养周期长，相信京东自营商城，物流很快，拿去店里换的，维修师傅说有不错，换完车的噪声小了很多，还在在买的发动机是汽车的心脏，润滑油的好坏对车辆的健康与否密切相关。好评一直从京东购买这款美孚一号机油，每次一万公里保养一次。"
    return render(request, 'Container/Analysis/analysis.html', {"context": context, "current": "analysis"})


def mining(request):
    #   To be updated
    return render(request, 'Container/Mining/index.html', {"current": "mining"})


def wordnet(request):
    #   DataClean data
    return render(request, 'IKEdata/wordnet.html', locals())


@csrf_exempt
def report(request):
    if request.method == 'POST':
        asset_data = request.POST.get('asset_data')
        data = json.loads(asset_data)
        if not data:
            return HttpResponse('没有数据！')
        if not issubclass(dict, type(data)):
            return HttpResponse('数据必须为字典格式！')
        # 你的检测代码

        sn = data.get('sn', None)

        if sn:
            asset_obj = models.Asset.objects.filter(sn=sn)  # [obj]
            if asset_obj:
                update_asset = asset_handler.UpdateAsset(request, asset_obj[0], data)
                return HttpResponse('资产数据已经更新。')
            else:
                obj = asset_handler.NewAsset(request, data)
                response = obj.add_to_new_assets_zone()
                return HttpResponse(response)
        else:
            return HttpResponse('没有资产sn，请检查数据内容！')

    return HttpResponse('200 ok')

IKEdata/templates/IKEdata/analysis.html
{% extends 'base.html' %}
{% load static %}

{% block title %}数据分析{% endblock %}
{% block css %}{% endblock %}

{% block breadcrumb %}
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            数据分析
            <small>data analysis</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> 主页</a></li>
            <li class="active">数据分析</li>
        </ol>
    </section>
{% endblock %}

{% block content %}


    <!-- Main content -->
    <section class="content">
        <div class="row">
            <!-- row -->
            <div class="col-md-12">
                <!-- jQuery Knob -->
                <div class="box box-solid">
                    <div class="box-header">
                        <i class="fa fa-bar-chart-o"></i>

                        <a href="{% url 'IKEdata:wordnet' %}"><span>知识图谱应用展示：词网</span></a>
                        <br>
                        <h3 class="box-title">自动摘要</h3>

                        <div class="box-tools pull-right">
                            <button type="button" class="btn btn-default btn-sm" data-widget="collapse"><i
                                    class="fa fa-minus"></i>
                            </button>
                            <button type="button" class="btn btn-default btn-sm" data-widget="remove"><i
                                    class="fa fa-times"></i>
                            </button>
                        </div>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <div class="row">
                            <td>
                                用了以后再追评一直用这个机油给车子保养，非常不错，相信京东自营。
                            </td>
                            <br>
                            <td>
                                不错，美孚一号大牌子，京东自营值得信赖，爱车非常适用，已经用好多次京东买了，顺便购买了更换机油服务，一步到位，发动机很安静，油耗也降低了一点点，谁用谁知道，希望多搞点活动。
                            </td>
                            <br>
                            <td>
                                一直用的银美孚一号 价格合适 自己保养车更放心 物流很快 一直信赖京东自营的东西选机油，先选SN级的，这是最高级，SL级是低配款，0W-30的意思是机油适用零度，流动性30的。
                            </td>
                            <br>
                            <td>
                                家中常备机油，便宜就先囤一个，一直用这个牌子推荐这家店铺非常不错哦第一次在京东平台上购买美孚一号，之前一直在市场上买，效果特别好，希望京东平台上的美孚保真保质，如果用的好，以后还会接着在京东上购买京东平台优惠力度大，值得推荐，大家快来抢购，以后还会在京东上购买，希望以后赠送礼品多点首先，金美孚一号这款油，一直用这个牌子，质量非常好，其次，京东自营下单，配送时效特别快，晚上下单第二天早上9点就收到了，省去了去实体店的苦恼，而且价格也非常优惠，有优惠券可以领，这款油保养周期长，相信京东自营商城，物流很快，拿去店里换的，维修师傅说有不错，换完车的噪声小了很多，还在在买的发动机是汽车的心脏，润滑油的好坏对车辆的健康与否密切相关。
                            </td>
                            <br>
                            <td>
                                好评一直从京东购买这款美孚一号机油，每次一万公里保养一次。
                            </td>

                            <!-- /.box-body -->
                        </div>
                        <!-- /.box -->
                    </div>
                    <!-- /.col (RIGHT) -->
                </div>
                <!-- /.row -->
            </div>

            <div class="col-md-6">
                <!-- BAR CHART -->
                <div class="box box-success">
                    <div class="box-header with-border">
                        <h3 class="box-title">词云</h3>
                        <div class="box-tools pull-right">
                            <button type="button" class="btn btn-box-tool" data-widget="collapse"><i
                                    class="fa fa-minus"></i>
                            </button>
                            <button type="button" class="btn btn-box-tool" data-widget="remove"><i
                                    class="fa fa-times"></i></button>
                        </div>
                    </div>
                    {% csrf_token %}
                    <div class="box-body">
                        <div id="wordcloud" style="height:400px;">
                            {% load static %}
                            <img width="400" src="{% static "images/wordcloud_all.png" %}" alt="runoob-logo">
                        </div>
                    </div>
                </div>
                <!-- /.box-body -->
            </div>
            <div class="col-md-6">
                <!-- DONUT CHART -->
                <div class="box box-danger">
                    <div class="box-header with-border">
                        <h3 class="box-title">情感分析</h3>

                        <div class="box-tools pull-right">
                            <button type="button" class="btn btn-box-tool" data-widget="collapse"><i
                                    class="fa fa-minus"></i>
                            </button>
                            <button type="button" class="btn btn-box-tool" data-widget="remove"><i
                                    class="fa fa-times"></i></button>
                        </div>
                    </div>
                    {% csrf_token %}
                    <div class="box-body">
                        <div id="Emotion_Analyse" style="height:400px;">
                            {% load static %}
                            <img width="400" src="{% static "images/Emotion_Analyses.png" %}" alt="runoob-logo">
                        </div>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col (RIGHT) -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
{% endblock %}
{% block script %}
    <script src="https://cdn.bootcss.com/echarts/4.2.1/echarts.min.js"></script>
    <script src="{% static 'adminlet-2.4.10/bower_components/jquery-knob/js/jquery.knob.js' %}"></script>
{% endblock %}

IKEdata/templates/IKEdata/collect.html
{% extends 'base.html' %}
{% load static %}
{% block title %}数据采集{% endblock %}

{% block css %}

{% endblock %}

{% block breadcrumb %}
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            数据采集
            <small>Data collect</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> 主页</a></li>
            <li>数据采集</li>
            <li class="active">资产详细</li>
        </ol>
    </section>
{% endblock %}

{% block content %}


    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">

                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">所有数据<small>(包含测试数据)</small></h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <table id="assets_table" class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <th>序号</th>
                                <th>来源</th>
                                <th>内容</th>
                                <th>作者</th>
                                <th>时间</th>
                                <th>链接</th>
                            </tr>
                            </thead>
                            <tbody>

                            {% for asset in all_data %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    {% if asset.source == 'JD' %}
                                        <td class="text-green text-bold">{{ asset.get_source_display }}</td>
                                    {% elif asset.source == "TEST" %}
                                        <td class="text-yellow text-bold">{{ asset.get_source_display }}</td>
                                    {% elif asset.source == "OTHER" %}
                                        <td class="text-blue text-bold">{{ asset.get_source_display }}</td>
                                    {% endif %}
                                    <td>{{ asset.content }}</td>
                                    <td>{{ asset.arthur }}</td>
                                    <td>{{ asset.time }}</td>
                                    <!--                  <td><a href="https://item.jd.com/5918444.html#comment">{{ asset.link }}</a></td>-->
                                    <td><a href="{{ asset.link }}">{{ asset.link }}</a></td>
                                </tr>
                            {% empty %}
                                <tr>没有数据！</tr>
                            {% endfor %}

                            </tbody>
                            <tfoot>
                            <tr>
                                <th>序号</th>
                                <th>来源</th>
                                <th>内容</th>
                                <th>作者</th>
                                <th>时间</th>
                                <th>链接</th>
                            </tr>
                            </tfoot>
                        </table>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>


{% endblock %}


{% block script %}

    <script src="{% static 'adminlet-2.4.10/bower_components/datatables.net/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'adminlet-2.4.10/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>

    <script>
        $(function () {
            $('#assets_table').DataTable({
                "paging": true,       <!-- 允许分页 -->
                "lengthChange": true, <!-- 允许改变每页显示的行数 -->
                "searching": true,    <!-- 允许内容搜索 -->
                "ordering": true,     <!-- 允许排序 -->
                "info": true,         <!-- 显示信息 -->
                "autoWidth": false    <!-- 固定宽度 -->
            });
        });
    </script>


{% endblock %}

IKEdata/templates/IKEdata/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}数据分析测试{% endblock %}

{% block css %}
    <link rel="stylesheet"
          href="{% static 'adminlet-2.4.10/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css' %}">
{% endblock %}

{% block breadcrumb %}
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>数据分析测试</h1>
        <form action={% url 'IKEdata:result' %} method="post">
            <label>
                {% csrf_token %}
                <textarea type="text" name="context" style="width: 600px;height:180px"></textarea>
            </label>
            <br/>
            <input type="submit" value="数据分析测试">
        </form>
    </section>
{% endblock %}


<script src="{% static 'adminlet-2.4.10/bower_components/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'adminlet-2.4.10/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>


IKEdata/templates/IKEdata/login_register.html
{% block login_register %}

    <div id="container">
        <!-- Header -->
        <div id="header">
            <div id="branding">
                <h1 id="site-name"><a href="/">宜氪数据&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a></h1>
            </div>
        </div>
        <!-- END Header -->
        <div class="main shifted" id="main">
            <div class="content">
                <!-- Content -->
                <div id="content" class="colM">
                    <div id="content-main">
                        <form action="{% url 'IKEdata:login' %}" method="post" id="login-form">
                            {% csrf_token %}
                            <div class="form-row">
                                <label class="required" for="id_username">用户名:</label>
                                <input type="text"
                                       name="username"
                                       autofocus=""
                                       autocapitalize="none"
                                       autocomplete="username"
                                       maxlength="150"
                                       required=""
                                       id="id_username" value="ike">
                            </div>
                            <div class="form-row">
                                <label class="required" for="id_password">密码:</label>
                                <input type="password"
                                       name="password"
                                       autocomplete="current-password"
                                       required=""
                                       id="id_password" value="Password.123">
                            </div>
                            <div class="submit-row">
                                <input type="submit" value="login">
                            </div>
                        </form>
                    </div>
                    <br class="clear">
                </div>
                <!-- END Content -->
                <div id="footer">
                    <p style="color: red;">{{ tips }}</p>
                    <p>
                        <strong>Copyright &copy; 2019
                            <a href="http://www.ike-data.com/" target="_blank">上海宜氪数据科技有限公司</a>.
                        </strong>
                        All
                        rights reserved.
                    </p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/Container/Analysis/analysisTest.html
{% extends 'base.html' %}
{% load static %}
{% block title %}数据分析测试{% if analysis_result %}结果{% endif %}{% endblock %}
{% block page_title %}数据分析测试{% if analysis_result %}结果{% endif %}{% endblock %}
{% block page_title_small %}Analysis Test {% if analysis_result %}Result{% endif %}{% endblock %}
{% block bread_crumbs %}
    <li class="mdui-float-left"><small>数据分析测试{% if analysis_result %}结果{% endif %}</small></li>
    <li class="mdui-float-left" style="margin: 0 5px"><small>/</small></li>
{% endblock %}
{% block analysis_test %}
    <div class="row mdui-typo">
        {% if analysis_result %}
            <div class="mdui-col-xs-12">
                <div class="mdui-card bw-md-card mdui-hoverable">
                    <div class="mdui-card-media">
                        <div class="mdui-card-media-covered bw-custom-covered bw-custom-covered-blue-grey mdui-clearfix">
                            <div class="mdui-card-primary">
                                <div class="mdui-typo-title-opacity" style="font-weight:700;">测试数据</div>
                            </div>
                        </div>
                    </div>
                    <div class="mdui-card-content">
                        {{ context }}
                    </div>
                </div>
            </div>
            <div class="mdui-col-xs-12">
                <div class="mdui-card bw-md-card mdui-hoverable">
                    <div class="mdui-card-media">
                        <div class="mdui-card-media-covered bw-custom-covered bw-custom-covered-blue-grey mdui-clearfix">
                            <div class="mdui-card-primary">
                                <div class="mdui-typo-title-opacity" style="font-weight:700;">自动摘要</div>
                            </div>
                        </div>
                    </div>
                    <div class="mdui-card-content">
                        {{ extract_text }}
                    </div>
                </div>
            </div>
            <div class="mdui-col-xs-12 mdui-col-sm-7">
                <div class="mdui-card bw-md-card mdui-hoverable">
                    <div class="mdui-card-content">词云</div>
                    <div class="mdui-card-media">
                        <img src="{% static 'images/wordcloud.png' %}" alt=""/>
                    </div>
                </div>
            </div>
            <div class="mdui-col-xs-12 mdui-col-sm-5">
                <div class="mdui-card bw-md-card mdui-hoverable">
                    <div class="mdui-card-content">关键字</div>
                    <div class="mdui-card-media">
                        <img class="wordcloud" src="{% static 'images/plt.png' %}" alt="wordcloud">
                    </div>
                </div>
            </div>
        {% else %}
            <div class="mdui-col-xs-12">
                <div class="mdui-card bw-md-card">
                    <form action="{% url 'IKEdata:analysis_test' %}" method="post">
                        {% csrf_token %}
                        <div class="mdui-card-content">
                            <div class="mdui-textfield">
                            <textarea class="mdui-textfield-input" placeholder="输入测试内容" name="context"
                                      required="required"></textarea>
                                <div class="mdui-textfield-helper">目前只支持输入中文</div>
                            </div>
                        </div>
                        <div class="mdui-card-actions">
                            <button class="mdui-btn mdui-ripple bw-btn-blue-grey" type="submit">测试</button>
                        </div>
                    </form>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}

templates/Container/Clean/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}数据清洗{% endblock %}
{% block page_title %}数据清洗{% endblock %}
{% block page_title_small %}Clean{% endblock %}
{% block bread_crumbs %}
    <li class="mdui-float-left"><small>数据清洗</small></li>
    <li class="mdui-float-left" style="margin: 0 5px"><small>/</small></li>
{% endblock %}
{% block clean %}
    <div class="row mdui-typo">
        <div class="mdui-col-xs-12">
            <div class="mdui-card bw-md-card mdui-hoverable">
                <div class="mdui-card-content">
                    <ol>
                        <li><a href="javascript:">新词与词性</a></li>
                        <li><a href="javascript:">停用词</a></li>
                        <li><a href="javascript:">同义词替换</a></li>
                        <li><a href="javascript:">语义分析</a></li>
                        <li><a href="javascript:">评论筛选</a></li>
                        <li><a href="javascript:">主数据标签清洗</a></li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/header.html
{% load static %}
<div class="mdui-appbar mdui-shadow-0 mdui-appbar-fixed"
     style="background-image: url('{% static "images/mask2.png" %}')">
    <div class="mdui-toolbar toolBar">
        <a href="javascript:" class="mdui-btn mdui-btn-icon" mdui-drawer="{target: '#left-drawer'}">
            <i class="mdui-icon material-icons">menu</i>
        </a>
        <a href="/" class="bw-logo">
            <img src="{% static 'images/logo_normal_w.png' %}" alt="">
        </a>
        <div class="mdui-toolbar-spacer"></div>
        <a href="{% url "IKEdata:sign_out" %}" class="mdui-btn mdui-btn-icon">
            <i class="mdui-icon material-icons">&#xe879;</i>
        </a>
    </div>
</div>

<div class="mdui-drawer sideBar" id="left-drawer">
    <ul class="mdui-list" mdui-collapse="{accordion: true}">
        <li class="mdui-list-item mdui-ripple {% if current == 'dashboard' %}bw-item-current{% endif %}">
            <span class="iconfont icon-dashboard mdui-list-item-icon mdui-icon material-icons mdui-text-color-white-icon"></span>
            <a href="{% url 'IKEdata:dashboard' %}" class="mdui-list-item-content">仪表盘</a>
        </li>
        <li class="mdui-list-item mdui-ripple {% if current == 'analysis_test' or current == 'analysis_result' %}bw-item-current{% endif %}">
            <span class="iconfont icon-edit mdui-list-item-icon mdui-icon material-icons mdui-text-color-white-icon"></span>
            <a href="{% url 'IKEdata:analysis_test' %}" class="mdui-list-item-content">数据分析测试</a>
        </li>
        <li class="mdui-list-item mdui-ripple {% if current == 'collect' %}bw-item-current{% endif %}">
            <span class="iconfont icon-save mdui-list-item-icon mdui-icon material-icons mdui-text-color-white-icon"></span>
            <a href="{% url 'IKEdata:collect' %}" class="mdui-list-item-content">数据采集</a>
        </li>
        <li class="mdui-list-item mdui-ripple {% if current == 'clean' %}bw-item-current{% endif %}">
            <span class="iconfont icon-cloud-o mdui-list-item-icon mdui-icon material-icons mdui-text-color-white-icon"></span>
            <a href="{% url 'IKEdata:clean' %}" class="mdui-list-item-content">数据清洗</a>
        </li>
        <li class="mdui-list-item mdui-ripple {% if current == 'analysis' %}bw-item-current{% endif %}">
            <span class="iconfont icon-dotchart mdui-list-item-icon mdui-icon material-icons mdui-text-color-white-icon"></span>
            <a href="{% url 'IKEdata:analysis' %}" class="mdui-list-item-content">数据分析</a>
        </li>
        <li class="mdui-list-item mdui-ripple {% if current == 'mining' %}bw-item-current{% endif %}">
            <span class="iconfont icon-shujuwajue mdui-list-item-icon mdui-icon material-icons mdui-text-color-white-icon"></span>
            <a href="{% url "IKEdata:mining" %}" class="mdui-list-item-content">数据挖掘</a>
        </li>
    </ul>
</div>

templates/login.html
{% load static %}
<form action="{% url 'IKEdata:login' %}" method="post">
    {% csrf_token %}
    <div class="mdui-valign login-card">
        <div class="mdui-center mdui-typo mdui-shadow-4 bw-login-center">
            <h1 class="mdui-text-center">宜氪数据 <small>IKE-data</small></h1>
            <p class="mdui-center">
                <label>
                    <i class="mdui-icon material-icons">&#xe851;</i>
                    <input type="text" name="username" placeholder="账号">
                </label>
            </p>
            <p class="mdui-center">
                <label>
                    <i class="mdui-icon material-icons">&#xe897;</i>
                    <input type="password" name="password" placeholder="密码">
                </label>
            </p>
            <p class="mdui-center">
                <button class="mdui-btn mdui-ripple" type="submit">登录</button>
            </p>
            <p class="mdui-text-center tips">
                {% if tips %}<i class="mdui-icon material-icons">&#xe001;</i>{{ tips }}{% endif %}
            </p>
        </div>
    </div>
</form>